### ISSUE TITLE
Forgot password not working

### ISSUE THREAD

**Issue by Nafizza** [Himanii07/microblog#3]
Feature: Password Reset
Priority: High
Scenario: Password reset email is not being sent
Given: A user has forgotten their password and is on the "Forgot Password" page
When: The user enters their email address and submits a password reset request
Then: The system should send an email with password reset instructions to the user’s email address
Actual: The system confirms that the email has been sent, but the user does not receive the reset email
Impact: Users are unable to reset their passwords, locking them out of their accounts.

**Comment by vNehal** [comment]
The issue with the 'Forgot Password' functionality has been resolved, and users can now successfully reset their passwords.
